hora=int(input("Selecciona la hora de salida: " ))
min=int(input("Selecciona los minutos de salida: " ))
seg=int(input("Selecciona los segundos de salida: "))
T=int(input("Selecciona el tiempo que ha tardado expresado en segundos: "))

hora = (hora * 3600)
min = (min * 60)
segTot= (hora + min + seg + T)
hora= (segTot // 3600)
r= (segTot - (hora * 3600))
min =  (r // 60)
seg= r - (min * 60)

print("Hora de llegada: ")
print(hora, ":", min, ":", seg)
